title: "Theory of Anticipation"
description: "The first mathematical framework for quantitative game design."
baseurl: ""
url: "https://akalouis.github.io"
markdown: kramdown
permalink: /:title/

# SEO Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO Settings
author:
  name: akalouis
  bio: "Creator of Theory of Anticipation"
  
social:
  name: akalouis
  links:
    - https://github.com/akalouis
    - https://doi.org/10.5281/zenodo.15826917
    - https://www.linkedin.com/in/lloyd-oh-3b765b314/

# SEO defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "akalouis"
